version: '2'
services:
    instasvc-app:
        image: instasvc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://instasvc-mysql:3306/instasvc?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    instasvc-mysql:
        extends:
            file: mysql.yml
            service: instasvc-mysql
